### ISSUE TITLE
AVIF images fail because of a timeout error

### ISSUE THREAD

**Issue by InnaAndreeva** [imgproxy/imgproxy#1000]
Hello!
I need to enable AVIF format in imgproxy, since this format supports compression on some pictures up to 90% 
My configuration
```bash
IMGPROXY_ENABLE_AVIF_DETECTION: true,
IMGPROXY_AVIF_SPEED: 8,
IMGPROXY_WRITE_TIMEOUT: 50
```
When I try open my image it fails with such error
```
[33mWARNING[0m [2022-10-11T06:27:35Z] Completed in 43.583945054s /unsafe/app_1440:q100/aHR0cHM6Ly9teS1jZG4uY29tL2ltYWdlcy9iaWctaW1hZ2UuanBn  [1mrequest_id[0m=LOimKR_cWZH4UaBiOIMhj [1mmethod[0m=GET [1mstatus[0m=499 [1mclient_ip[0m=x.x.x.x [1merror[0m="Request was cancelled after 43.583886242s"
```
This problem appears on large images (size:1440 and larger with quality parameter)
I need to distribute pictures in different formats (png, jpg, webp, avif) with different settings (q100, size:1440, size:2880)

Requests to imgproxy are proxied via nginx (I did not set proxy timeouts (proxy_connect_timeout, proxy_send_timeout, proxy_read_timeout etc.)

Imgproxy instance deployed in Openshift cluster with big limits - 3 cpu with memory 3Gi and for requests we set 1 CPU and memory 1Gi.

How can I configure imgproxy to serve images with enabled AVIF format?

Is there any way to optimize the conversion to AVIF of large images?

**Comment by DarthSim** [comment]
Hey @InnaAndreeva!

Which version of imgproxy do you use? AVIF saving speed was quite improved in the latest versions.

Also, it doesn't look like your config is properly set. You wrote that you set IMGPROXY_WRITE_TIMEOUT to 50 but the log record you've shown says that the request was timed out after 43 seconds which is less than the configured timeout.

**Comment by InnaAndreeva** [comment]
Hi!
I upgraded imgproxy image to [latest docker image](https://hub.docker.com/layers/darthsim/imgproxy/latest/images/sha256-163c0f8afb1e6a4d6f11a4103378355b35cbe390d594e586c09432b13022ba74?context=explore)

I get a timeout error if I request an image multiple times
I use such imgproxy settings for image - `resizing_type:fill/size:2880::0:0` with q:100

**Comment by DarthSim** [comment]
> i request an image multiple times

This actually may be the cause. imgproxy has a maximum number of images that it can process simultaneously a.k.a. concurrency. It is controlled by the `IMGPROXY_CONCURRENCY` config and its default value is twice the number of CPUs. In your case, since your requested number of CPUs is 1, the default concurrency of your imgproxy instance is 2.

When you send multiple requests to imgproxy, it can process only IMGPROXY_CONCURRENCY images simultaneously. The rest of the requests are waiting in a queue. Let's assume that your instance's concurrency is 2, you send 10 requests, and each request takes 2 seconds to be processed. Here's what happens:

- imgproxy takes 2 requests from the queue and processes them for 2 seconds.
- imgproxy takes the next 2 requests from the queue and processes them for 2 seconds, too. But since they waited for 2 seconds in the queue, the response time for these requests will be 4 seconds.
- The response time for the next 2 requests will be 6 seconds, etc. The response time for the last pair of requests will be 10 seconds.

So here's the question: does your imgproxy instance show you good timings when you send a single request?

Here's what I'd do:
- Set `IMGPROXY_CONCURRENCY` explicitly. Since your CPU limit is 3, I'd set `IMGPROXY_CONCURRENCY=6`.
- Use lower quality. `q:100` is way too much for AVIF and, actually, for the rest of the formats too. The higher the quality, the longer the encoding time.

**Comment by InnaAndreeva** [comment]
Sorry for the long answer :)
Upgrading to a new version of imgproxy and tuning the config for AVIF solved my problem
Thank you very much for your help!
