### ISSUE TITLE
Q / Feature: Maximum crop limit 

### ISSUE THREAD

**Issue by fenos** [imgproxy/imgproxy#1102]
Hello,
It would be nice if we could specify a maximum size in which the image could be resized, if the original image or the requested sizes exceed the limit we default to the max limit

Image the scenario where I have an image `4000x4000` I would like to set a maximum width & height in which the image could be resized for example `2000x2000` 

given the following scenarios:

- `w:1400` -> should result in `w:1400,h:2000` instead of `w:1400,h:4000`
- `w:3000` -> should result in : `w:2000,h:2000` instead of `w:3000,h:4000`
- `w:3000,h:3000` should result in : `w:2000,h:2000` instead of `w:3000,h:3000`

I've made a [PR](https://github.com/supabase/imgproxy/pull/13) in our forked version that we use at Supabase

I would love to send this PR to imgproxy - any feedback before doing so will be appreciated, the implementation uses 2 optional environment variables:

- `IMGPROXY_CROP_MAX_WIDTH`  
- `IMGPROXY_CROP_MAX_HEIGHT`

**Comment by DarthSim** [comment]
Hey Fabrizio!

Unless `enlarge` is not set to `true`, `width` and `height` act like "max width" and "max height". You can add this logic to your wrapper:

* `?width=1400` => `.../w:1400/h:2000/...`
* `?width=3000` => `.../w:2000/h:2000/...`
* `?width=3000&height=3000` => `.../w:2000/h:2000/...`

Also, I'd control max width/height with processing options instead of config. imgproxy uses its processing pipeline in different places other than processing the image itself: preparing watermarks, preparing images for object detection, etc. Configs will affect all these things, which is incorrect. You can create a `default` preset with all the options that you'd like to be applied by default.

**Comment by fenos** [comment]
@DarthSim AH! the `default` preset approach seems exactly what I needed!!
Thanks a lot!
