### ISSUE TITLE
Q: Limit file size and resolution as options

### ISSUE THREAD

**Issue by fenos** [imgproxy/imgproxy#1103]
Hello me again 😄 I hope you are well!

I have a use case in which I would like to allow certain users to have a higher limit of file size (`IMGPROXY_MAX_SRC_FILE_SIZE`) and others a lower limit, as well as for the resolution (`IMGPROXY_MAX_SRC_RESOLUTION`).

At the moment is a global configuration.

In my system, I have the file size information, and I can easily prevent the request depending on the file size.
However, I don't have the resolution since I'm not parsing the image.

What will it be the best approach for this with imgproxy?

Regards

**Comment by DarthSim** [comment]
Hey Fabrizio!

These parameters are global by design. If we allow redefining them with processing options, an attacker can use it to bypass the restrictions unless you sign the URLs. Thus, security restrictions should be defined somewhere where an attacker can't change them, and I see the only place like this – the global config.

If just need strong restrictions to be applied to one group of users and not be applied to another, I guess, the easiest solution is to have two different imgproxy installations with different restrictions.

You could also utilize imgproxy Pro's feature of getting the image info, but using a paid version is not an option for you as far as I remember.

**Comment by fenos** [comment]
Thanks, @DarthSim 

Since we proxy the request to an internal imgproxy instance having it as a processing option is doable on our side, as well as for users that sign URLs.

Maybe we could implement these limits as processing options but turn them off by default?
 
The image info approach seems also reasonable but it would mean higher latency since we'd need to check the values before allowing to transform the image, not too keen on that.

Yhea, currently we would like to give feature parity to our customers that self-host imgproxy, they can, however, upgrade themself to the Pro version (which we would encourage)

 Although never say never 👍 we really embrace the power imgproxy

**Comment by DarthSim** [comment]
> Maybe we could implement these limits as processing options but turn them off by default?

This may work 🤔

**Comment by DarthSim** [comment]
Okay, I added this to the `latest` build :)

The `IMGPROXY_ALLOW_SECURITY_OPTIONS` config enables the following options:
* `max_src_resolution` (`msr`)
* `max_src_file_size` (`msfs`)
* `max_animation_frames` (`maf`)
* `max_animation_frame_resolution` (`mafr`)
