### ISSUE TITLE
Crash on broken source image

### ISSUE THREAD

**Issue by dmkl** [imgproxy/imgproxy#1161]
Hi, we get a 500 error code on resizing an image that got uploaded to S3 broken somehow. Should `imgproxy` recognise an invalid image or catch an exception and return a better error code like 422?

![111](https://github.com/imgproxy/imgproxy/assets/652653/511a18c8-e6be-444d-b717-3f9bf05011da)

**Comment by DarthSim** [comment]
Hey @dmkl!
Sounds like a good idea. Added to the `latest` build

**Comment by bsboris** [comment]
Hi @DarthSim! As of the current latest build, at least for some broken files, we observe a crash of Imgproxy:

The response is: 
`{status: 500, body: "Internal error", headers: [...]}`

And in the logs:
```
ERROR   [2023-09-11T07:11:51Z] Completed in 157.529958ms <REDACTED>  request_id=6TwOjMtr-wH76A6Wb_x3_ method=GET status=500 client_ip=127.0.0.1 error="VipsJpeg: Premature end of JPEG file\nVipsJpeg: Corrupt JPEG data: found marker 0xd9 instead of RST2"
/app/vips/vips.go:390 github.com/imgproxy/imgproxy/v3/vips.(*Image).Save
/app/processing/processing.go:345 github.com/imgproxy/imgproxy/v3/processing.ProcessImage
/app/processing_handler.go:428 main.handleProcessing.func3
/app/processing_handler.go:426 main.handleProcessing
/app/server.go:114 main.buildRouter.withCORS.func1
/app/server.go:165 main.buildRouter.withPanicHandler.func2
/app/router/router.go:102 github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP
/usr/local/go/src/net/http/server.go:2939 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2010 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_arm64.s:1198 runtime.goexit
```

If it is not possible to avoid such crashes for all possible inputs, can at least this message  "VipsJpeg: Premature end of JPEG file\nVipsJpeg: Corrupt JPEG data: found marker 0xd9 instead of RST2" be added to the response body in this case?

**Comment by DarthSim** [comment]
Geez, don't scare me 😄 500 response is not a crash, it is a caught error. Crash is an unexpected process termination.

imgproxy doesn't show the exact error in the response for security reasons. A regular user doesn't need it, an attacker can use it. If you want to see the exact error in the response, you can use the `IMGPROXY_DEVELOPMENT_ERRORS_MODE` config.

**Comment by bsboris** [comment]
> Geez, don't scare me 😄

Sorry, my bad, should be more specific. Won't happen again!

> 500 response is not a crash, it is a caught error.

Well, yes, but, as you know, 5xx status means "there is something wrong with the server", and 4xx status means "there is something wrong with client request". 4xx status looks more suitable for broken file input.

> imgproxy doesn't show the exact error in the response for security reasons.  

We don't need exact error, we need a way to be sure that it is malformed source file causing non-200 response, not network troubles or other temporary issues.

`IMGPROXY_DEVELOPMENT_ERRORS_MODE` is a last resort, as it may contain stack traces, as stated in docs.

**Comment by DarthSim** [comment]
> Well, yes, but, as you know, 5xx status means "there is something wrong with the server", and 4xx status means "there is something wrong with client request". 4xx status looks more suitable for broken file input.

Yeah, you're right. Sorry, I misunderstood your point.

Unfortunately, vips doesn't give us info about whether the error happened during the loading or in any other place. And because of the way vips loads images (it doesn't decode pixels until we need them) the fact that the loading function didn't return any errors doesn't mean anything. So we have to determine it based on the error text only. The check is stupidly simple: if the error contains a certain substring, we treat it as an image-loading error. I added more image-loading error markers to the latest build.
