### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by negator** [imgproxy/imgproxy#1177]
Any plans to support streaming? 

https://www.libvips.org/2019/11/29/True-streaming-for-libvips.html

**Comment by DarthSim** [comment]
Hey @negator!

It doesn't seem that libvips streaming would work well with imgproxy.

1. We need to know if the image processing succeeded before we start writing the response body. Otherwise, we won't be able to set proper response status, headers, etc.
2. We need to know if the image download succeeded before we start processing it. Otherwise, we won't be able to use a fallback image.
3. Go-to-C and C-to-Go calls have performance penalties. Streaming implementation would require lots of C-to-Go calls, thus – lower performance.

**Comment by negator** [comment]
Right makes sense thanks. I was thinking perhaps you could eliminate one of the two copies of the buffered image (one created on download, one created after processing) thereby reducing your memory consumption. 

The idea would involve using a ring buffer in a C struct that is continually populated by incoming bytes, and continually read by libvips as it processes the image. Similarly, you could implement a target ring buffer that is written to by libvips and read out to the response. You could perform checks on the resulting VipsImage after processing is complete to allow you to set proper response headers. This should eliminate all of the expensive C-to-Go calls, but still incurring the (far less expensive ) Go-to-C calls.

Anyways, just an idea. Thanks for humoring me :)
