### ISSUE TITLE
Clarification on IMGPROXY_CONCURRENCY limits re: pricing

### ISSUE THREAD

**Issue by erulabs** [imgproxy/imgproxy#1178]
Hello!

  I can't sort out how the global IMGPROXY_CONCURRENCY is intended to work with regards to the pricing plans when running multiple copies of imgproxy. On imgproxy.net, the hover-over for concurrency says:

> The number of images that can be processed concurrently by a single instance can be configured with the IMGPROXY_CONCURRENCY config. For instance, assuming your license allows for a max concurrency of 32, if there are 16 instances running and each of them has been set to have an IMGPROXY_CONCURRENCY of 2, in total, your instances can concurrently process 32 images. Requests that exceed this limit are not rejected but are instead placed in the queue.

This seems to imply there is some sort of distributed tracking of all licensed imgproxies? We seem to be able to get considerably higher thruput from a fleet of 10 imgproxies without setting IMGPROXY_CONCURRENCY or a license key (as much as 150 req/sec for a somewhat large test image! Impressive!).

Is the wording meant to imply that if we pay for Pro, we can increase the concurrency of a single instance to 32? Or is the wording correct and there is a global, per license-key, ratelimiting system? I wasnt able to find anything in the code, so I assume the wording on the website is just a bit confused.

If I'm correct, you might consider adding a sentence like `Pro users can increase the IMGPROXY_CONCURRENCY of a single instance past the default limit of 16`.

Thank you! Looking forward to putting imgproxy into production!

**Comment by DarthSim** [comment]
Hey!

imgproxy Pro works as fast as imgproxy OSS. imgproxy Pro is about additional features, not about speed. So if you are happy with features of OSS version, feel free to use the open-source version. But purchasing the Pro license would suport imgproxy development ;) If you could find 15 minutes, we could manage a call and discuss how we could be helpful to each other.

For both imgproxy and imgproxy Pro, the default concurrency is twice the CPUs number. It can be changed with the `IMGPROXY_CONCURRENCY` config, yet the default concurrency works best in most cases.

imgproxy Pro uses the overall concurrency (i.e. the sum of IMGPROXY_CONCURRENCY of all the instances using the same license) as a metric of usage for pricing. imgproxy Pro instances report their IMGPROXY_CONCURRENCY value to our licensing server. You can't find anything like this in the code because Pro's source is closed.

We're aware that the current pricing description may be confusing to some users, so we're in the process of rebuilding the whole pricing block to make it more clear.

**Comment by erulabs** [comment]
@DarthSim Ah, thank you! I really appreciate the comment, thank you!

Feel free to close this issue - although it may be worth adding a clarifying sentence to the pricing hover-over!
