### ISSUE TITLE
First Crop and then Resize

### ISSUE THREAD

**Issue by bonafernando** [imgproxy/imgproxy#123]
I'm trying to crop an image and then resize the result like this: 

`/rt:crop/w:186/h:186/el:1/g:fp:0.6:0.3/rs:fill:100:100/`

1. It doesn't execute this multiple transformations.
2. If you try to run this same option several times in a row, it generates different results.

I would like to check if it is expected and understand how could I crop and resize.

Thank you.

**Comment by DarthSim** [comment]
Hi,

It is expected behavior. Processing options should not be treated like processing pipeline since one is tuned for the maximum performance. Read more about this here: https://github.com/DarthSim/imgproxy/blob/master/docs/about_processing_pipeline.md

Currently, it's not possible to crop and resize, but I'll think about this feature.

Alternatively, you can do 2-pass processing: build imgproxy URL for cropping and use it as the source URL for resizing. This would require additional resources for encoding/decoding, but it's better than nothing.

**Comment by bonafernando** [comment]
Hi, @DarthSim. Thank you for consider this feature request. Yes, we are currently using this 2-pass processing alternative, but it would be great to have a preset with the option to resize after the transformation.

**Comment by jeepey** [comment]
Also ran into this issue, being able to resize an image after we did a crop would be great

**Comment by rdm** [comment]
I'm doing crop+resize (building a srcset for a crop) by passing the imgproxy crop url as the base for an imgproxy resize url. This works reasonably well, with two issues:

(1) it looks like /plain/ in the url gets handled wrong when there's two of them in the url. My "solution" was to only use /plain/ once and to base64 encode the inner url.

(2) Performance on cropping an image seems poor (base image being on the order of 50MB -- typical digital camera stuff). I'm currently playing with the environmental variables which tune the performance of the thing (can't use jemalloc on alpine, currently) to see if any of those can help me out.

**Comment by DarthSim** [comment]
Hi there,

I'm doing some work preparing 2.3 release, and crop-then-resize is one of the features upcoming. Follow the news.

**Comment by DarthSim** [comment]
Somehow I forgot to introduce [crop](https://github.com/imgproxy/imgproxy/blob/master/docs/generating_the_url_advanced.md#crop) option from `v2.3.0` here.
