### ISSUE TITLE
How to get width and height of original img?

### ISSUE THREAD

**Issue by leopold1989** [imgproxy/imgproxy#1275]
could u offer some specific exmaple api about how to get img infomartion,is it has to use pro version?

**Comment by DarthSim** [comment]
Hey @leopold1989!

[Getting an image info](https://docs.imgproxy.net/latest/usage/getting_info) is a Pro feature, yes.

**Comment by Tymek** [comment]
Getting at least the dimensions/ratio is very useful for static site generators. There already is a way to get this information from headers if `EnableDebugHeaders ` is enabled. The `imagemeta` package is already public. @DarthSim Do you consider open-sourcing this as an endpoint? Or allowing a contribution without a fork?

For my use case, Thumbor has /meta/ info, and this missing feature prevents me from switching to imgproxy. I'm using `thumbor-wand-engine` because of HEIC support and experimenting with `thumbor-vips-engine`.

**Comment by DarthSim** [comment]
@Tymek Sorry, but we won't add the `/info` endpoint to the OSS version.

Also, even with all my love for imgproxy, I believe that using vips directly or via Sharp at build time is more suitable for static site generators.
