### ISSUE TITLE
Watermark text does not support special characters

### ISSUE THREAD

**Issue by Ross-Hunter** [imgproxy/imgproxy#1297]
I am getting a 500 when attempting to use `&` as a character in watermark text.

**Comment by mstaack** [comment]
do you use correct encoding?

show me your url please

**Comment by DarthSim** [comment]
Hey @Ross-Hunter!

`watermark-text` accepts text in the [Pango markup](https://docs.gtk.org/Pango/pango_markup.html). Since it is an HTML-like language, it has the same special characters: `<`, `>`, and `&`. All you need is to replace them with `&lt;`,  `&gt;`, and `&amp;` respectively, or just use an HTML-escaping function from your language. Guess it is worth mentioning in the docs 🤔

**Comment by Joe-Degler** [comment]
Stepping in for ross here.

I think we should've filed this issue in `imgproxy.rb` https://github.com/imgproxy/imgproxy.rb

I think our default assumption would've been that the gem would take care to either make sure the `watermark_text` was compliant by encoding it correctly, or raised an error directly, instead of returning an URL.

**Comment by DarthSim** [comment]
I don't think it's really possible. A user may want to use the Pango markup in the `watermark_text` value, and if the gem escapes every `watermark_text` value, it would ruin the markup.

The other way is to try to predict if the user tries to use markup or not. This will most probably lead to more confusion.

The third way is to try to parse the `watermark_text` value and raise an error if the parsing fails. There we'll need something like Nokogiri or Ox just to check the value of a single option. Not a good idea IMHO. Also, we don't check values in `imgproxy.rb` at all.

The fourth way is to add an argument to the `watermark_text` option that disables the Pango markup. This is doable and, probably, is a good idea. But the markup will be enabled by default anyway since this is the current behavior, so the problem of "the issue was not obvious to figure out" won't be solved.

And last but not least: you can wrap the `watermark_text` value with `CGI::escapeHTML` right in your code, which will solve the problem completely 🙂

**Comment by Ross-Hunter** [comment]
> Hey @Ross-Hunter!
> 
> `watermark-text` accepts text in the [Pango markup](https://docs.gtk.org/Pango/pango_markup.html). Since it is an HTML-like language, it has the same special characters: `<`, `>`, and `&`. All you need is to replace them with `&lt;`, `&gt;`, and `&amp;` respectively, or just use an HTML-escaping function from your language. Guess it is worth mentioning in the docs 🤔

That was the issue. I did not see anything in the docs about special characters in watermark text.

I can tell that imgproxy.rb is properly base64 encoding the value, but if that value contains an ampersand, then imgproxy (go) returns a 500 -- however if I `CGI.escapeHTML(watermark_text)` then it works as intended.

Thanks for the help @DarthSim!

**Comment by DarthSim** [comment]
No problem! I'll definitely add a warning about this to the docs.

**Comment by Ross-Hunter** [comment]
And of course, now I find it in the docs 🤦 

https://docs.imgproxy.net/features/watermark#text-watermarks

I think I kept reading this and not quite registering that you *must* use pango markup to support special characters.
