### ISSUE TITLE
slow s3 download times

### ISSUE THREAD

**Issue by yohanb** [imgproxy/imgproxy#1337]
Hi!
I'm seeing some abnormally long download times coming from s3 and wondering if you have any guidance around why this could happen and how to debug.
For example, we can see here that download time is ~1.14s for a 2.5MB image:
![image](https://github.com/user-attachments/assets/7a8340cb-69e8-42ad-9619-64879f2a1a46)

Sadly, the tracing doesn't give any deeper understanding as to what may be the cause.

Setup: 
pod resources: requests 2vCPU and 256Mi;  limits 4vCPU and 512Mi
nodes: graviton c8g.xlarge
CPU pressure: 10-20%/requests
Mem pressure: ~50%/requests

Thanks! 🙏

**Comment by yohanb** [comment]
I tried setting debug logs for http2 (`GODEBUG=http2debug=1`) and I'm seeing a lot of the following error message:
```
"2024/10/07 16:35:28 http2: Transport failed to get client conn for ###.s3.amazonaws.com:443: http2: no cached connection was available"
```
It seems to be happening at every request.  I think that this means the http keep-alive connection pool might not be working as expected.

---
![image](https://github.com/user-attachments/assets/ad8ebbd9-84c3-4e91-8f33-903fbdf7584d)

**Comment by yohanb** [comment]
Thanks @DarthSim .  Any suggestions about how you would go about debugging the slow download speed?
The pod and s3 bucket are both in the same region and the VPC endpoint is configured and working correctly.

**Comment by DarthSim** [comment]
As I mentioned before, it's most likely that the problem lies somewhere outside of imgproxy. I'd probably deploy an image with curl and traceroute to the same cluster to test the downloading speed without imgproxy involved and check the routing to the S3 endpoints.

I'm testing imgproxy+S3 in ECS+EC2 from time to time, yet I didn't notice any downloading speed problems. So, unfortunately, I'm not much of a help here.
