### ISSUE TITLE
Change aspect ratio with fill or fit options without resizing

### ISSUE THREAD

**Issue by sevrai** [imgproxy/imgproxy#1380]
Hello, 

Is there a way to change the aspect ratio of the image without resizing it (either width or height will remain the same) ?

For example, I would like to get a square of a landscape original image. To do it now, I can use the `resize` option but I need to know the actual dimensions of the image and set as width and height the max of these dimensions.

In the docs, an `Extend aspect ratio` is present but does not seem to do what I want. 
I could use the `/info` endpoint but this requires an extra call.

Thank you in advance !

**Comment by DarthSim** [comment]
Hey @sevrai!

imgproxy doesn't have a processing option that just changes the aspect ratio, but you can imitate it with some limitations using the `fill-down` resizing type.

Let's assume all your images have at least one dimension less than 10000 px. Then you can use `.../rs:fill-down:10000:10000/...`. imgproxy doesn't enlarge an image by default, so if either of its dimensions is less than 10000 px, imgproxy won't scale it at all. The `fill-down` resizing type tells imgproxy to crop the image to the requested aspect ratio nevertheless it was scaled or not.

The limitations are:

- You can't use the `enlarge` option. Otherwise, imgproxy will upscale the image. But considering your task, you probably don't need this.
- You should ensure that all your images have at least one dimension shorter than the sizes you provide to `rs`. The good news is that the sizes you can use with `rs` are limited only by the max `int64` value (9223372036854775807). I am pretty sure you have images of that size 😅 On the other hand, using some reasonable values may protect you from showing some enormous images.

**Comment by DarthSim** [comment]
I guess, the [extend_aspect_ratio](https://docs.imgproxy.net/usage/processing#extend-aspect-ratio) option is what you're looking for then

**Comment by sevrai** [comment]
That works perfectly, thank you !
