### ISSUE TITLE
gifs are broken

### ISSUE THREAD

**Issue by ajsharp** [imgproxy/imgproxy#242]
Even when trying to access a gif through image proxy without any resize params, it only shows/returns the first frame. I installed via heroku, which is using the "latest" docker tag. 

Filestack url: http://imgproxy.foliohd.com/insecure/plain/https://media.giphy.com/media/eNRJtDi4c9BggIzJrd/giphy.gif
Original: https://media.giphy.com/media/eNRJtDi4c9BggIzJrd/giphy.gif

**Comment by ajsharp** [comment]
Ping @DarthSim

**Comment by DarthSim** [comment]
Please read the documentation carefully https://docs.imgproxy.net/#/image_formats_support?id=animated-images-support

Since processing of animated images is pretty heavy, only one frame is processed by default. You can increase the maximum of animation frames to process with the following variable:

* `IMGPROXY_MAX_ANIMATION_FRAMES`: the maximum of animated image frames to being processed. Default: `1`.

**Note:** imgproxy summarizes all frames resolutions while checking source image resolution.
