### ISSUE TITLE
Feature: face detection and blur filter

### ISSUE THREAD

**Issue by GNURub** [imgproxy/imgproxy#301]
Add Filter forma face like [cloudinary](https://cloudinary.com/cookbook/blur_or_pixelate_faces).

**Comment by DarthSim** [comment]
Hi,
This is an upcoming feature of imgproxy pro, and won't be included in OSS version.

**Comment by jburgyan** [comment]
It would be interesting to create an opensource fork, where face detection is enabled. Since both opencv and libvips are opensource, I don't see any obstacles of creating such a version. Probably this is a feature which is needed in 99% of use cases, but a $500 subscription is way overpriced for those who don't need advanced features like video processing, etc
