### ISSUE TITLE
Support AVIF

### ISSUE THREAD

**Issue by Tom910** [imgproxy/imgproxy#456]
Hi, do you have plans to implement AVIF format? It's new-generation image format https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4 which will be supported in new version Chrome 85 https://caniuse.com/#feat=avif . I think is a great feature and more imgproxy users will appear on the wave of hype

**Comment by DarthSim** [comment]
Yup, I'm thinking about this

**Comment by Tom910** [comment]
chrome 85 released and now 1 browser support AVIF

**Comment by foobargeez** [comment]
+1 for avif support - https://jakearchibald.com/2020/avif-has-landed/

**Comment by tinect** [comment]
+1 Waiting for it :-)

**Comment by Johnzzon** [comment]
AVIF is a game changer for sure, would love support for this format in imgproxy!

**Comment by carlmjohnson** [comment]
https://github.com/libvips/libvips/issues/1570 was closed as fixed.

**Comment by legopin** [comment]
Looks like work is being done on it
https://github.com/imgproxy/imgproxy/commit/1bd789df4e09ca9b45ee368b4d830e8d2d7735ee

**Comment by legopin** [comment]
Would there be a flag similar to `IMGPROXY_ENABLE_WEBP_DETECTION` that uses the `Accept` header to automatically determine avif image support?

**Comment by DarthSim** [comment]
Well, yeah, I'll probably add this, but here's the thing...
I freaking hate the format auto-detection feature :) It complicates the code, it works badly with CDNs and caches, it is insecure since headers can't be signed, and stuff. I highly recommend using the `picture` tag with multiple sources rather than auto-detection on the imgproxy side.
As for AVIF, there's another problem. If you save your image to AVIF and JPEG with the same quality factor you'll see that the AVIF file is bigger than JPEG. If you want to optimize your image by saving it to AVIF, you need to decrease the quality factor, which is impossible while using format auto-detection. So it seems like we need something like AVIF quality coefficient to decrease the quality factor automatically in addition to format auto-detection.

**Comment by jbergstroem** [comment]
> Well, yeah, I'll probably add this, but here's the thing...

Tbh I think this functionality has more merit "in front" of imgproxy; most likely in the cache layer. From my end, I use cloudflare workers to modify requests going back to imgproxy and therefore also can modify things like cache keys or how I want imgproxy to act.

**Comment by DarthSim** [comment]
Ok guys, it feels like I finalized AVIF support implementation. Here are some notes on it:

- There's a new config `IMGPROXY_FORMAT_QUALITY` that allows to specify the default quality per format. By default, imgproxy uses this config to set the default AVIF quality to 50 as it gives us the same average SSIM for AVIF output as quality 80 for JPEG.
- There are `IMGPROXY_ENABLE_AVIF_DETECTION` and `IMGPROXY_ENFORCE_AVIF` configs. imgproxy prefers AVIF over WebP, so if you enable both AVIF and WebP detection and browser supports them both, imgproxy will use AVIF.
- imgproxy won't switch to AVIF automatically if the source image format supports animation. This is because AVIF sequence is not currently supported by browsers. I'm going to implement a check that the source image is actually animated, but this will probably go to the next release.
