### ISSUE TITLE
PDF support causes runaway goroutines

### ISSUE THREAD

**Issue by sagebind** [imgproxy/imgproxy#484]
We appreciate the new formats and features being added to imgproxy, makes me glad we chose to use imgproxy to power our previewing system. When upgrading to version 2.15.0 (pro), I noticed that support for PDF as a source was added, so I decided to give it a try in our software to see what happens. We generate WebP "seed files" from almost every file using a slower method and give that to imgproxy as a source, but during the window of time between when a file is first added and before the seed is generated, we optionally will give imgproxy the original file as a source for "snappier" previews if we can.

When adding the option to feed PDFs directly into imgproxy, we noticed that connections to imgproxy began timing out 15-ish minutes after deployment, so we rolled back. Digging into our collected metrics, I noticed that imgproxy pods that were given PDFs as input files began creating goroutines at an alarming rate without decreasing:

![imgproxy goroutines](https://user-images.githubusercontent.com/2192863/95230340-5fad2080-07c7-11eb-93b6-82d42251f92a.png)

(Slopes end when the pods were killed and replaced with new pods.)

Memory usage remained relatively normal during this time, but latency for establishing a new connection went up, and our proxy layer began timing out after 15 seconds trying to establish a connection to imgproxy.

I'm not sure what exactly went wrong here, but I supect one of these two possibilities:

* There is a goroutine leak somewhere in the PDF implementation.
* PDFs are simply expected to be slow, and at our volume of traffic (>10K requests/minute) imgproxy simply gets piled up with too many concurrent requests.

Though I am suspecting the first possibility (hence this issue) because we have imgproxy configured with `IMGPROXY_CONCURRENCY=50` per instance, and >400 goroutines seems really high when this configuration is set.

Thoughts?

**Comment by DarthSim** [comment]
Hi!

I have just tried to spam imgproxy v2.15.0 with 200 concurrent requests of PDF processing while the concurrency was set to 50. I have got 400+ goroutines, but their number didn't grow. Since imgproxy doesn't do anything special with PDFs, ones shouldn't cause goroutines leak. Anyway, I'd appreciate some samples of your PDFs and imgproxy URLs.

You should know that `IMGPROXY_CONCURRENCY` != maximum of concurrent requests. `IMGPROXY_CONCURRENCY` is the number of images that can be processed simultaneously. If the number of concurrent requests if greater than concurrency, some requests will be put into a queue. The maximum number of concurrent requests can be configured with `IMGPROXY_MAX_CLIENTS `, and it's `IMGPROXY_CONCURRENCY * 10` by default (500 in your case). Every request is processed in its own goroutine. Goroutines are also cast while working with channels. So if you have 200+ concurrent requests, you'll get 400+ goroutines with ease.

Also, PDFium is not thread-safe, and libvips wraps all PDF loading operations with mutexes. Thus if some of your PDFs are heavy to load, this may cause a jam in this place.

I always recommend scaling imgproxy horizontally rather than vertically. It's better to have 10 pods with a concurrency of 5 than a single pod with a concurrency of 50. Try to split your pods into smaller ones and see if it helps.

**Comment by sagebind** [comment]
Thanks for your detailed response! Those numbers do make sense, though I'm still not entirely sure why connections to imgproxy were timing out if they ought to have been accepted (up to 500) and put in a queue for image processing. That part I'm still a bit puzzled by.

> Also, PDFium is not thread-safe, and libvips wraps all PDF loading operations with mutexes.

Ah good to know, that was probably the real source of the bottleneck then; a couple dozens of large PDFs could easily put an imgproxy instance out of commision if we reach the concurrency limit with all PDF requests, since new requests will be queued, but the PDF requests will be processed more-or-less one at a time anyway.

> I always recommend scaling imgproxy horizontally rather than vertically.

I guess we've done both, with `IMGPROXY_CONCURRENCY=50` and 16 pods. I'll look into adjusting this to be more horizontal and see if that helps us. (it should since it increases the total number of parallel PDF operations.)

**Comment by sagebind** [comment]
OK, so it turns out I'm *not* losing my sanity, and there indeed seems to be *some* sort of problem here. I'm not sure what, it isn't runaway goroutines, but it does indeed put imgproxy out of commission. Here's a new metrics graph:

<img width="1420" alt="Screen Shot 2020-10-08 at 3 56 06 PM" src="https://user-images.githubusercontent.com/2192863/95512685-d17b9a80-097e-11eb-90fc-7e56deb7cbc0.png">

I also grabbed the logs from this pod in order to correlate activity with the graph above. What I found is that, at 14:34:12, this particular imgproxy instance was given a PDF as a source file for making a thumbnail. Log message:

    Started /insecure/w:250/h:250/rt:fit/bg:255:255:255/bga:0.0/[REDACTED].webp

As soon as this log message was emitted, not a single image request completed after this point. This can be observed by looking for log messages such as `Completed in 170.317633ms /insecure/blah`. There are tons before this point, and zero after this point. So it seems like sending this request *immediately* puts the pod out of commission.

After this point there are still plenty of `Started /insecure/blah` messages. But actually, there are exactly 99 of them between 14:34:18 and 15:12:27. Over this time period in the metric graph is when you see the number of goroutines steadily rise. This 99 likely corresponds to the value of `IMGPROXY_MAX_CLIENTS`. (I had increased the pod count and reduced `IMGPROXY_CONCURRENCY` to `10`, so the effective value for `IMGPROXY_MAX_CLIENTS` should be `100`.)

Finally, at 15:12:49, requests to the `/health` endpoint (which previously _were_ succeeding during this time period) stopped responding, and so the kubelet restarted the pod, which is reflected on the graph as the goroutine count resetting back to normal.

Curious and surprised, I decided to attempt to reproduce this locally. No high traffic, no Kubernetes, just the Docker image (still the v2.15.0 tag BTW) and some manual requests to it. And to my surprise (or relief for being reproducible 😉), I was able to get the exact same behavior with a fresh Docker container. Simply send a request with a PDF as the source in it, and then while waiting try to send another request with literally anything as the source (in this case I used a plain old JPEG). As I am writing this, I am still waiting, and neither the initial PDF request nor the following JPEG request have returned after 10 minutes. Also, aborting the request doesn't do anything, though I wouldn't really expect it to either.

Now unfortunately, I cannot share the PDF file that caused this with since it is data confidential to our customers, but I did want to make sure that it wasn't something wrong with the PDF itself. It seems that is perhaps the case, since I couldn't reproduce it with [this dummy PDF](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf).

At the moment, I am trying to find another PDF that it is OK to share that also gives this behavior so that you can reproduce, but I guess my other question is: is there a way to timebox or timeout these requests? I wouldn't mind if a problematic PDF or two showed up a couple times an hour as long as imgproxy was able to abort the operation after 5 seconds or so.

My other question is, why does such a PDF put imgproxy immediately out of commission? I get that there's a mutex around PDF operations, but then why are subsequent non-PDF requests hanging when my concurrency level is `10`? I'd expect imgproxy to continue processing up to 9 non-PDF operations at a time while the 1 PDF request is running.

**Comment by DarthSim** [comment]
Ok, we finally found that is was a "bad" PDF that causes the issue. It turns out that libvips wraps PDF-loading operations with a global lock https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfiumload.c#L220. This, of course, leads to the locking of an unpredictable number of operations. Seems like it should use a separate mutex for PDFs. I'll try to prepare a PR that fixes the problem and patch the libvips build inside a Pro image. I'd appreciate it if you could provide a sample of that "bad" PDF so I could test a fix. I can guarantee it won't go anywhere from my laptop's hard drive which is encrypted.

> At the moment, I am trying to find another PDF that it is OK to share that also gives this behavior so that you can reproduce, but I guess my other question is: is there a way to timebox or timeout these requests? I wouldn't mind if a problematic PDF or two showed up a couple times an hour as long as imgproxy was able to abort the operation after 5 seconds or so.

Unfortunately, we can't stop libvips operations in the middle. imgproxy surely checks the timings between the operations, but if an operation takes a long time, imgproxy has to wait until it's done.

We can set a hard timeout right in the server settings, but this will lead to "zombie requests": the request is timeouted but still waits for a long-running operation to stop. This will lead to the usage of additional resources and slowing down the entire imgproxy instance. IMHO this doesn't look anyhow better than the current case.

**Comment by sagebind** [comment]
I haven't been able to find a PDF yet that I can share that exhibits this problem, but I can keep looking. Though whatever aspect of these PDFs that cause the problem must not be _too_ uncommon, since when we enable PDF support in production, multiple PDFs from multiple customers of ours seem to cause this. It's definitely not a "heaviness" factor; imgproxy/vips seems to accept a large, image-heavy 200MB PDF just fine and returns in a second or two. When this issue happens, it hangs for at least 15 minutes or more, consuming very little CPU, so I am assuming that some particular element in the PDF triggers a codepath with a deadlock of some sort in PDFium.

**Comment by DarthSim** [comment]
By heaviness, I don't mean the file size but something inside the PDF doc that is hard for PDFium to render.

**Comment by DarthSim** [comment]
@jcupitt I have considered poppler in the first place, but as you mentioned it's licensed under GPL. We can't afford any GPL libs to be used by imgproxy since we have a commercial version of it. More of it, poppler licensing is a kind of complex thing: it is based on Xpdf which is also GPL. Xpdf has a kind of commercial license, but poppler doesn't since it's based on GPL software. So it seems like there is literally no way to use poppler in non-GPL software :(

**Comment by sagebind** [comment]
OK, apologies for the delay, but I have finally acquired a PDF document that reproduces this problem that I can post here. I've removed all images, vector elements, text, and metadata from this PDF, and yet it still causes some sort of deadlock that causes imgproxy/vips/PDFium to never return; it just hangs forever no matter how long you wait. I've also uncompressed the PDF stream itself to be easier to inspect:

[deadlock-pdf-blank-stripped-uncompressed.pdf.zip](https://github.com/imgproxy/imgproxy/files/5459179/deadlock-pdf-blank-stripped-uncompressed.pdf.zip)

Note that all the PDF tools at my disposal see no issue with this PDF and simply display it (yes it is a blank page) correctly, including Acrobat, PDF.js, macOS Preview, Chrome, and Ghostscript. Now I'm not too knowledgeable about the PDF format or PostScript, but I have been spending a considerable amount of time fiddling around with it. My suspicion is it has to do with what appears to be an embedded color profile, since if I remove it and replace references to it with a reference to device CMYK, imgproxy seems to no longer hang and instead returns a thumbnail instantly.

Also, is it not the case that Google Chrome uses PDFium internally for its builtin PDF viewer? I find it interesting that Google Chrome had no problem whatsoever rendering this PDF. Perhaps libvips is using an outdated version that has a fix for this already?

Is there a more appropriate place to report this bug?

**Comment by jcupitt** [comment]
Hi @sagebind,

That's interesting, I tried at the command-line using PDFium 4290 and git master libvips:

```
john@yingna ~/pics $ /usr/bin/time -f %M:%e vipsthumbnail deadlock-pdf-blank-stripped-uncompressed.pdf
35816:0.06
john@yingna ~/pics $ vipsheader tn_deadlock-pdf-blank-stripped-uncompressed.jpg 
tn_deadlock-pdf-blank-stripped-uncompressed.jpg: 128x83 uchar, 3 bands, srgb, jpegload
```

ie. it makes the thumbnail in 60ms and needs 35mb of memory. It's a blank white square (as you say).

Do you know the libvips and PDFium versions you see the deadlock with?

**Comment by sagebind** [comment]
If pkg-config is to be believed, I am using libvips 8.10.1, I'm not sure about PDFium. I am using one of the latest prebuilt imgproxy-pro Docker images, @DarthSim would probably know the PDFium version included.

**Comment by jcupitt** [comment]
Could you try `vipsthumbnail` at the command-line? If that locks up, we've got a nice, simple test case.

**Comment by sagebind** [comment]
Yes, I am able to reproduce with the `vipsthumbnail` command, though only with the `libpdfium.so` packaged in the imgproxy Docker image. So far, I am trying various versions of PDFium from https://github.com/bblanchon/pdfium-binaries/releases and am not able to reproduce. So I am wondering if there is something wrong in particular with the `libpdfium.so` I have been given.

**Comment by jcupitt** [comment]
Wow, that's strange. It's great you've found a fix anyway.

**Comment by DarthSim** [comment]
Thank you for digging this out! I found what causes this issue. I build PDFium to reuse as much system-wide installed libraries as possible instead of statically linking ones that are distributed with PDFium. It occurred that lcms2 that [comes with PDFium](https://pdfium.googlesource.com/pdfium/+/refs/heads/master/third_party/lcms/) is very patched. It seems like one of those patches fixes this issue. I'll try to release the fixed image ASAP.

**Comment by DarthSim** [comment]
I'm really sorry for the huge delay. Looks like I make it work in the latest build.

**Comment by sagebind** [comment]
@DarthSim Indeed, it looks like this problem is totally fixed in the very latest image. Thanks!
