### ISSUE TITLE
[Question] Is there a way to get the original picture?

### ISSUE THREAD

**Issue by hitech95** [imgproxy/imgproxy#497]
I would like to know how to serve the original file, without any modification.

**Comment by jpalumickas** [comment]
I think this one related to https://github.com/imgproxy/imgproxy/issues/476

**Comment by DarthSim** [comment]
The best way is to serve it by the direct URL bypassing imgproxy. Thus you'll eliminate overhead added by imgproxy ('cause it still needs to download the image), and free some imgproxy workers.

**Comment by hitech95** [comment]
In my case the imgs are hosted on s3, and I would like to not have public access to the bucket for public original quality links.

**Comment by DarthSim** [comment]
If it's ok for your case, you can have your bucket private and generate temporary signed URLs for your images. You can also put CloudFront in front of your S3. Honestly, imgproxy is not the best solution to serve the originals. As I said before, imgproxy doesn't stream your image, it downloads it, and this will lead to a huge lag in comparison with direct access. If you still want to serve originals through imgproxy, there are two options:

1. Don't pass any processing options. In this case, imgproxy won't actually return the original, because it will encode and decode the image removing its meta and converting the color profile to sRGB. But the size of the image will be unchanged.
2. Wait until #476 is implemented and pass all the possible formats to the skipping option. In this case, I'd close this issue as it duplicates #476.

**Comment by hitech95** [comment]
Option 1 is perfect.
My imgproxy is cached from cloudflare and we are actually using an s3 compatible bucket.
So CloudFront is a no go. That is why I've asked that. Even if the image is reencoded there is no problem.
The fact that ùi can get the original image  resolution is already a great thing. (I have a galòlery where I can also show the uncropped/notresized image in a modal)

**Comment by DarthSim** [comment]
Looks like this can be closed
