### ISSUE TITLE
Question: Client hints and max size

### ISSUE THREAD

**Issue by josephschorr** [imgproxy/imgproxy#520]
Apologies if I missed a reference on how to do this in the documentation.

I'm currently testing imgproxy with client hints and, so far, it is working extremely well. However, as client hints are currently not widely supported, I'd like to know if there is a way to *also* set a maximum width/height for the image, such that if the client hints are not present, imgproxy would fallback to the max width/height. Currently, when I try adding the width+height to the transformation URL, imgproxy ignores the client hints and instead uses the size specified (which seems like the correct behavior, but perhaps this should be an option?)

Thanks!

**Comment by DarthSim** [comment]
Hey Joseph,

There's no such thing as max width/height in imgproxy and, unfortunately, won't be. I don't like client hints much since they can't be signed, and it looks like a very niche feature. Adding some additional options for such a feature means overcomplication of the code and its maintenance.

Feel free to fork the repo and change processing options parsing to apply client hints in the end.
