### ISSUE TITLE
Vulnerability warnings (Container Registry vulnerability scanning)

### ISSUE THREAD

**Issue by flunderpero** [imgproxy/imgproxy#583]
I just pushed the 2.16.2 docker image to our Google Cloud Container Registry and it reported 61 vulnerabilities.

```
High | 7.1 | — | glibc | CVE-2019-25013
Medium | 4.6 | — | systemd | CVE-2019-3844
Medium | 4.6 | — | systemd | CVE-2019-3843
Medium | 5 | — | pcre3 | CVE-2020-14155
Medium | 5.9 | — | glibc | CVE-2020-1751
Medium | 5 | — | libidn2 | CVE-2019-12290
Medium | 5 | — | glibc | CVE-2021-3326
Medium | 6.4 | — | libbsd | CVE-2019-20367
Medium | 4.3 | — | libgcrypt20 | CVE-2019-12904
Medium | 6.8 | — | gcc-8 | CVE-2018-12886
```

(The number in the second column is CVSS score.)

I did not assess the critically of any of the issues, they might not affect anything at all. I thought I share it with you, though.

**Comment by DarthSim** [comment]
Hey Peter,

Thanks for sharing! I'd not worry much about the vulnerabilities you listed:
- **GLib**: imgproxy uses the latest version built from the source. However, the system version of it is included in the image, that's why the scanner reports CVE. But, again, imgproxy doesn't use the system version.
- "gcc-8": it doesn't look like this CVE can be used in the container. Also, there's no Go base image with a newer GCC, so it looks like this can be quickfixed. Anyway, it's ARM-only.
- All other listed libs are not used by imgproxy. You can check this with `ldd`.

**Comment by dkarlovi** [comment]
@DarthSim looking at the same issue (security scanner tagging issues), it seems there's a bunch of them in the latest version of the image. Is the image not meant to be used for production deploys? 

Namely, I can see a bunch of tools I didn't expect to see in a production-ready image, especially considering Imgproxy is a static binary. For example, perl, tar, gpg, these are all present in the image, but I don't really see why. Is the binary doing exec() on them in some way? Is the image maybe meant for development only and not recommended for production deployments? Thanks.

**Comment by DarthSim** [comment]
Our Docker image is absolutely ready for production and is used by tons of companies of different scales in production.

If you take a look at the found vulnerabilities, you'll find that all of them don't have fixes at the moment. We update all the packages on every build, and we use the latest available versions of all the libraries we build from the source, so when fixed versions are available, we'll upgrade to them.

Also, all the vulnerabilities but one is low severity. The only medium-severity vulnerability is found in a Go package. Unfortunately, scanners that don't work with source code can't determine if the vulnerable code is actually used. And imgproxy doesn't use the vulnerable code from `aws-sdk-go/service/s3/s3crypto` exactly because it is vulnerable.

imgproxy's Docker image is based on the official Debian image which contains some stuff that imgproxy doesn't actually use. Yet this stuff is needed for things like a package manager. We could probably build a "clean" image that wouldn't contain anything but imgproxy itself and its dependencies, but this would incomplex extending the image by our users.

**Comment by dkarlovi** [comment]
OK, so if I understood correctly, you recommend building the clean version of the image ourselves. Thanks!

**Comment by DarthSim** [comment]
I honestly don't see any reason for that. I recommend using our official Docker image since I can't guarantee proper work otherwise.

**Comment by dkarlovi** [comment]
We're doing image scanning so these false positives create overhead and "known bad" state which might mean some "unknown bad" slips by, not to mention the image size.

It gives me an opportunity to try out [Chiselled Ubuntu](https://ubuntu.com/engage/chiselled-ubuntu-images-for-containershttps://ubuntu.com/engage/chiselled-ubuntu-images-for-containers) images.

Will try it out and if it makes sense, we could PR the clean image Dockerfile you could offer side by side with the existing image.
