### ISSUE TITLE
Trimming PNGs with alpha channel

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#645]
Hi,

We are in the process of migration from out homemade solution to imgproxy (thanks for the great product, by the way!) and encountered confusing behaviour while trimming PNGs with alpha channel. It's exactly the same issue we've already [stumbled with using libvips](https://github.com/libvips/libvips/issues/1866). Looks like this can be fixed by leaving out `background` argument to `find_trim`, but I'm not comfortable enough with C/Go to check it myself.

**Comment by DarthSim** [comment]
Hey!
Sorry for the delay, I was on vacation without access to GH.

Well, there's a couple of things about `trim`:
- `vips_find_trim` flattens the image with black (imgproxy does this explicitly, but anyway). This may lead to cutting off semi-transparent black parts.
- If you don't specify a color to trim, imgproxy gets one from the top left corner of the image. If the top left corner differs from the background color, trimming may work incorrectly.

Both things are discussable and may be fixed in the future, but currently, we have what we have :(

**Comment by bsboris** [comment]
Hi, thanks for the response! Hope the vacation was nice =)

As far as I can see, this is not the case with this exact image in question (attached). There is no semi-transparent  black parts, and background color is uniform across all area. Can you have a look, please?

![Logo_TV_2015](https://user-images.githubusercontent.com/591230/120994743-7314ef00-c78d-11eb-8c8c-c0a1470cfac6.png)

**Comment by DarthSim** [comment]
Ah, I see. After flattening, this image becomes fully black, so vips can't find the trimming boundaries. I think, it's better to flatten with magenta or something like this... I'll try to make a release with this fix soon.

**Comment by bsboris** [comment]
Have you seen this comment to the linked issue: https://github.com/libvips/libvips/issues/1866#issuecomment-716694667?
Looks like vips trims correctly if background is not set explicitly.

**Comment by DarthSim** [comment]
Yeah, my bad, `vips_find_trim` flattens ith white by default, that's why your image works fine without `background` set. I still think magenta is a better color for flattening than white though.

**Comment by elcolto** [comment]
Hi, thanks for that issue. On my usecase I have some similar problem with a black alpha shadow in the image.

>I'll try to make a release with this fix soon.

Is this still the plan?

**Comment by DarthSim** [comment]
Ugh, sorry for not mentioning this. [v2.16.4](https://github.com/imgproxy/imgproxy/releases/tag/v2.16.4) uses magenta for the alpha, so this should fix the problem.
