### ISSUE TITLE
vips_colourspace: no known route from 'cmyk' to 'srgb'

### ISSUE THREAD

**Issue by treffner** [imgproxy/imgproxy#673]
Unable to convert one image.
Log: 
```
vips_colourspace: no known route from 'cmyk' to 'srgb'
```

Here is the same issue:
https://github.com/imgproxy/imgproxy/issues/39

I installed yesterday with
```bash
curl -Ls https://github.com/imgproxy/imgproxy/archive/master.tar.gz \
  | tar -xz --strip-components 1 -C .
CGO_LDFLAGS_ALLOW="-s|-w" /usr/local/go/bin/go build -o /usr/local/bin/imgproxy
```

I don't know if you need informations about the host:
```bash
uname -a
Linux serv47797592-02.secure-node.at 4.19.0 #1 SMP Fri Nov 20 21:47:55 MSK 2020 x86_64 GNU/Linux

OS: linux, Debian GNU/Linux 10 (buster) (chroot) - I think it runs RHEL underneath
Processor: 8 cpus, 64bit, little endian, Intel(R) Xeon(R) E-2286G CPU @ 4.00GHz
CC version: cc (Debian 8.3.0-6) 8.3.0
Git version: git version 2.20.1

/usr/local/go/bin/go version
go version go1.16.6 linux/amd64
```

I add the image as attachment.

![Ratiopharm-logo](https://user-images.githubusercontent.com/17121556/126599970-15fae8cf-7c56-4d8d-af9c-edb110f4a301.jpg)

**Comment by DarthSim** [comment]
Hey Thomas!

It seems like you're using an old version of libvips. I'd recommend using the official Docker image instead of building imgproxy from the source. I spend a lot of time keeping the dependencies updated and patched so everything works as intended. If you build imgproxy from the source, you'll have to deal with all the issues I already fixed in the image.

**Comment by treffner** [comment]
Thank you!
It works with docker.
