### ISSUE TITLE
Configure base URL + use source URL from same host

### ISSUE THREAD

**Issue by jebax** [imgproxy/imgproxy#687]
Hi there,

In our current implementation of imgproxy (using helm), we're setting `IMGPROXY_BASE_URL`. We'd like to start serving images from S3 in conjunction with images on a legacy server (which is our current base URL e.g. `https://my-legacy-server.com`). 

The first step of this change would be to remove our base URL configuration, and start passing fully qualified source URLs to imgproxy (e.g. `/plain/https://my-legacy-server.com/images/test.jpg`). But obviously it's hard to do this without breaking our images between deployments, because you can't have a base URL configured and pass in a fully qualified source URL at the same time.

It would be nice if you could have both at the same time, if the hostname of the source URL matches your base URL. What do you think?

**Comment by DarthSim** [comment]
Hi Joel,

Sorry for the late response.

I'm preparing the 3rd version of imgproxy so v2 is kind of feature-freezed now. I could add this feature to v3 but I don't think you can wait for its release.

Since you need this functionality for a short time only, I'd recommend using a fork. The patch is really simple, you should add the following lines before this one https://github.com/imgproxy/imgproxy/blob/master/processing_options.go#L358

```go
if strings.HasPrefix(unescaped, conf.BaseURL) {
	return unescaped, format, nil
}
```

**Comment by DarthSim** [comment]
@jebax I had to make a release, so I added this feature to v2.17.0
