### ISSUE TITLE
Avif/Webp settings for Cloudflare

### ISSUE THREAD

**Issue by quard8** [imgproxy/imgproxy#791]
Hi! 

I'd like to use AVIF and WEBP formats with Cloudflare CDN, do you have info or tutorial how to do it? Currently I disabled nextgen formats due of cache issues on different browsers

**Comment by quard8** [comment]
Nevermind, find solution (added Lossly settings and removed webp, avid support in imgproxy)

**Comment by fkowal** [comment]
I am still testing but i think i managed to configure it to make it compatible with CF

1. your DNS IP needs to "regional" / without anycast
2. enable Vary for images https://developers.cloudflare.com/cache/advanced-configuration/vary-for-images/ (url need to have an extensions jpg/webp/avif) but without it CF Vary for images doesn't work
3. imgproxy has IMGPROXY_ENFORCE_WEBP=true & IMGPROXY_ENFORCE_AVIF=true (this conflicts with CF cache expected behaviour) this is why Header rewrite is needed
4. USER -> CF -> Header Rewrite Service -> ImgProxy
5. Reponse needs to return `Vary: Accept` header (this seems to be a default imgproxy behaviour)

CF requires respecting the order of `Accept` header
ie. `Accept: image/webp,image/avif,....` response `ContentType: image/webp`
Abore *Enforce* settings don't comply with this behaviour (avif if preferred)
that why a `Header Rewrite Service` does +- `req.headers.split(",").first() +-`
this way imgproxy receives a request with `Accept: image/webp` (only)
