### ISSUE TITLE
Dynamic/regex support for PATH_PREFIX

### ISSUE THREAD

**Issue by markedmondson** [imgproxy/imgproxy#806]
I'm wondering if we could get IMGPROXY_PATH_PREFIX to support regex matching? Here's the use case, I'll do my best to explain it as it's maybe a relatively unique use-case.

We sign Cloudfront URLs with a secure cookie, for other assets in our application they sit at `/secure/<company name>/*`, our Imgproxy assets go through `/img/*`. We currently sign the custom Cloudfront policy with `/*/<company name>/*` and sign our Imgproxy served URLs. I'd like to avoid the signing and use the cookie throughout.

Since we can only sign the cookie with a [single resource](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html#private-content-custom-policy-statement-cookies-values), in order to get both to work through the signed cookie, we'd have to set the policy path to `/*`, which clearly means we can't ensure the companies assets are restricted.

If we could put a wildcard in the IMGPROXY_PATH_PREFIX, eg `/img/.*/` then we could maintain the same policy URL of `/*/<company_name>/*` and all would be good.

How feasible is this as an option?

Thanks!

**Comment by DarthSim** [comment]
Hey @markedmondson!

I try to avoid the usage of RegExp in the router. The current implementation works with bare strings as this is faster, simpler, and decreases the possibility of any mistakes. In this implementation, the value of `IMGPROXY_PATH_PREFIX` is simply added to every route.

Since your case is pretty rare, I'd rather not add the dynamic prefix support as this may affect many users. The thing you need can be achieved with a simple proxy in front of imgproxy. For example, Nginx can be configured to trim the prefix from the path before redirecting the request to upstream (in your case - imgproxy).

**Comment by markedmondson** [comment]
Thanks for the quick reply Sergey!

Actually I think I've had some success using a Cloudfront Function to do the URL rewriting (effectively a proxy like you suggest). Hopefully this'll help someone in the future.
