### ISSUE TITLE
go build fails with "error loading module requirements"

### ISSUE THREAD

**Issue by YChebotaev** [imgproxy/imgproxy#824]
1. Installed `go` and `libvips` via `apt-get` on debian 10.11
2. Downloaded latest code from `https://github.com/imgproxy/imgproxy/archive/master.tar.gz`
3. Then `CGO_LDFLAGS_ALLOW="-s|-w"   go build -o /usr/local/bin/imgproxy`

Getting error:

```
go: error loading module requirements
```

Full output: https://pastebin.com/b7153nYp

**Comment by DarthSim** [comment]
Hey @YChebotaev!

Debian Buster provides pretty old versions of Go and libvips. Your issue is probably related to the old Go version. But even if you install a newer version of Go, you probably won't be able to build imgproxy with the libvips version from the Debian Buster repo. Building libvips from the source is not an easy task too as it needs a lot of dependencies so every feature works as expected.

So, I recommend using dockerized imgproxy as it contains all the dependencies updated and tuned. Building imgproxy and libvips from the source and keeping it updated most probably bring you more headache than a performance boost.
