### ISSUE TITLE
High CPU usage and dropped requests

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#850]
We are running Imgproxy Pro instance under relatively heavy load, and one strange issue happens repeatedly.

It starts by our users reporting that pictures on their sites (served by Imgproxy) are not loading. Inspecting our monitoring tools and logs, we observe high CPU usage, spikes in traffic and Imgproxy log filled with "Request was cancelled after XXXs" errors. There is not much can be done to fix this, only restarting Imgproxy helps. After that things go back to normal. Until the next occurrence. This can happen up to several times a day and is pretty annoying.

Now to the interesting stuff. Server status during the incidents looks like this (incidents highlighted by red frames).

CPU utilization:  
![image](https://user-images.githubusercontent.com/591230/164457710-d9b01d4c-210a-4113-a7ae-efe037f4f756.png)

In/Out traffic:  
![image](https://user-images.githubusercontent.com/591230/164457941-b8958b68-00fd-4b14-9610-1892228a1908.png)

ENV file:
```
IMGPROXY_BIND=127.0.0.1:8081
IMGPROXY_NETWORK=tcp4
IMGPROXY_TTL=31556952 # 1 year
IMGPROXY_ALLOW_ORIGIN=*
IMGPROXY_LOG_LEVEL=info
IMGPROXY_QUALITY=89
IMGPROXY_STRIP_METADATA=false
IMGPROXY_DOWNLOAD_TIMEOUT=10
IMGPROXY_CONCURRENCY=16
IMGPROXY_ENABLE_VIDEO_THUMBNAILS=true
IMGPROXY_MAX_SRC_FILE_SIZE=10485760
```

No other services are running on the server, except Nginx to proxy and cache requests to Imgproxy.  
Please, let me know if I should provide you with any additional details.

I was unable to find out what exact events causes this behavior. But it looks like Imgproxy stucks in some kind of loop, downloading something(?) and not serving incoming requests properly.

Please, please, look into this. This is currently the only thing ruining our, otherwise flawless, experience.

**Comment by DarthSim** [comment]
Hey Eugene,

The important thing we know for now:
1. You use Nginx to proxy requests to imgproxy
2. Requests are canceled, not timed out.
3. Things go back to normal after restart.

Here's what I suspect:
Something (probably some bad image) blocks all the processing workers, and new requests are stuck in the queue. Nginx doesn't get a response for a time and cancels the request. So we need to find out what request cause the issue.

Here's what we can do:
1. If you collect logs (I believe you do), you can take a look at a couple of things:
   * In imgproxy logs: requests that started but weren't completed. `request_id` should help you here.
   * In Nginx access logs: requests with status `504`. One of the first ones before the peak is probably one we are looking for.
   * In Nginx error logs: things like `upstream timed out`. Same as above, one of the first ones before the peak is probably one we are looking for.
2. When the issue occurs again, kill imgproxy with `ABORT` signal. If you use pure Docker, you can do so with `docker kill -s ABRT imgproxy_container_id`. When Go apps are killed with this signal, they print their stack trace, and I'd like to look at it if we won't find the issue cause before.

We could set up a Zoom call and inspect logs together if you like.

**Comment by bsboris** [comment]
Hi, Sergey! Thank you for the quick response and detailed explanations. It really helps!

After further investigation I think I've got some idea what might be going on (and now I feel pretty stupid for not checking all the logs myself before opening this issue): just about the incident time Nginx error log starts to fill with errors like  
`open() "cache/a/b/c" failed (24: Too many open files)`. 

So, the suspected scenario is that Nginx cache hits open files limit due to random traffic peak, and Imgproxy works under heavy load without any cache. This explains CPU peak, In/Out traffic graph shape. One thing left unclear is why restarting Imgproxy helps Nginx cache to start working back again.

Anyway, I've increased `worker_rlimit_nofile` in Nginx config. Will monitor this situtation and come back with updates.

Thanks again!

**Comment by DarthSim** [comment]
As we know, everything is a file in Linux including network connections. Due to peak traffic and missed cache, lots of connections to imgproxy are opened, and they flood your ulimit. When you restart imgproxy, all the connections are dropped and your ulimit is cleaned a bit.

If you're an Nginx Plus user, I'd recommend you to do the following:

1. Set `max_conns` of the upstream server to the same value as `IMGPROXY_CONCURRENCY`. Thus Nginx won't create more connections to imgproxy than imgproxy can process simultaneously. imgproxy does a little bit of work before checking the concurrency limit (like a signature check, processing options parsing, etc), so you may want to increase `max_conns` a bit.
2. Set `keepalive` option of the upstream to make Nginx reuse connections instead of creating new ones.
3. Set `queue` of the upstream to some reasonable value so Nginx won't return 502 if upstream server is busy. Unfortunately this option only available in Nginx Plus, and all previous steps are pretty useless without it :(

Also, it's a good idea to put a caching CDN in front of your server. This will dramatically reduce the headache ;)
