### ISSUE TITLE
AVIF and big size images

### ISSUE THREAD

**Issue by Tom910** [imgproxy/imgproxy#935]
Hi, we started using AVIF and found a problem with optimizing large images (more than 2MB) in that case imgproxy spends a lot of time and RPS down to minimum values. From my perspective will be good if imgproxy has options that limited image size which would optimize imgproxy. Like IMGPROXY_AVIF_LIMIT_SIZE

**Comment by DarthSim** [comment]
Hi @Tom910!
Try to set `IMGPROXY_AVIF_SPEED=8`. This will slightly reduce the AVIFs compression level but will speed up AVIF encoding significantly.

**Comment by Tom910** [comment]
@DarthSim thanks for the answer. In our case, even IMGPROXY_AVIF_SPEED=8 creates problems because anyway works much slowly then webp

**Comment by SuperOleg39** [comment]
@DarthSim we checked that lower quality for AVIF works better, with latest Docker image (up from 3.5.0 to 3.7.0).
For example, with default `quality`, presets like `width:xxx` or `dpr:2` for big images works faster than WebP, and produce smaller by 60-70% images.

But with the same `quality`, e.g. `quality:70`, AVIF processed slower a much and produced a larger image, because of that we will try to use `format_quality`, found good quality comparsion in the https://www.industrialempathy.com/posts/avif-webp-quality-settings/ article.

There is some technical problem with `format_quality`, started a separate issue https://github.com/imgproxy/imgproxy/issues/938

https://github.com/imgproxy/imgproxy/issues/938

**Comment by DarthSim** [comment]
Since #938 is fixed, can we close this?

**Comment by SuperOleg39** [comment]
Yes, thanks you!

Looks like the cases when AVIF is still slower will be slow and with WebP, so if we will find something interesting, will back with another questions)
