### ISSUE TITLE
Image XMP metadata

### ISSUE THREAD

**Issue by schonert** [imgproxy/imgproxy#978]
I'd like to request support for extracting XMP metadata from images through the `/info` path 🙏

**Comment by DarthSim** [comment]
Added to the `latest` build

**Comment by schonert** [comment]
@DarthSim great news. Thanks!

**Comment by schonert** [comment]
It's working as expected 👍🏻 do you use a third party to extract metadata? It's seems like files containing IPTC return an empty IPTC object - which is why we need XMP in the first place. 

If so, maybe we could try updating that package?

**Comment by DarthSim** [comment]
imgproxy uses a homebrew IPTC parser. The code is partially inspired by [libiptcdata](https://libiptcdata.sourceforge.net/) and supports all the tags from the [specification](http://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf).

The thing is that when we talk about IPTC, we usually talk about the IPTC-IIM metadata format. But globally IPTC Photo Metadata Standard includes XMP. That's why some IPTC extraction tools map XMP data to IPTC Photo Metadata Standard names following the [specification](https://iptc.org/std/photometadata/specification/iptc-pmd-techreference_2022.1.json).

**Comment by schonert** [comment]
Appreciate the detailed response! Thanks for adding this
