### ISSUE TITLE
Resizing doesn't work without a signature 

### ISSUE THREAD

**Issue by StitiFatah** [imgproxy/imgproxy#994]
Hi, 

I would prefer not to use a signature, putting restrictions into my CDN is sufficient for my use case. 

I've tested using the same s3 image with the same imgproxy instance, first with a signature and secondly without a signature (by removing salt + key from the env variables), with the signature everything work as intended but without it resizing doesn't work (although image format modification works fine). 

I'm using the v3.7 (got the same output with v3 too) from docker hub and my env variables are as follow : 

IMGPROXY_BIND=0.0.0.0:5000
IMGPROXY_ENABLE_WEBP_DETECTION=true
IMGPROXY_USE_S3=true
AWS_ACCESS_KEY_ID=***
AWS_SECRET_ACCESS_KEY=***
IMGPROXY_S3_REGION=fra1
IMGPROXY_S3_ENDPOINT=fra1.digitaloceanspaces.com

Is that an intended behavior ? Thanks in advance.

**Comment by DarthSim** [comment]
Hey @StitiFatah!

You didn't provide a URL example, but I believe it's something like this:

```
https://your-domain.com/rs:fit:100:100/plain/http://image/url.jpg
```
If I'm right, then you're missing the signature part. The signature part should always be presented in the URL. However, if the URL signature is not configured, the signature part may contain literally anything:

```
https://your-domain.com/_/rs:fit:100:100/plain/http://image/url.jpg
```

The reason why it doesn't work in the first case is that imgproxy treats  `rs:fit:100:100` as a signature and just ignores it since the URL signature is not configured.

**Comment by StitiFatah** [comment]
> Hey @StitiFatah!
> 
> You didn't provide a URL example, but I believe it's something like this:
> 
> ```
> https://your-domain.com/rs:fit:100:100/plain/http://image/url.jpg

Yes you're completely right, that's what I did and it's working fine now with a dummy signature, it was mentioned in the docs https://github.com/imgproxy/imgproxy/blob/master/docs/generating_the_url.md , sorry for the inconvenience and thanks !
